### ISSUE TITLE
Hilos Windows Form Proyecto

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo-kem#1]
[Hilos Windows Form Proyecto.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-equipo-kem/files/15133723/Hilos.Windows.Form.Proyecto.pdf)

**Comment by IrvinSanchez-dev** [comment]
DADO A LA RUBRICA DE EVALUACION OBTUVIERON UN 19% 

**LES HIZO FALTA MAS IMAGENES, EL TOTAL ERA 20 Y SOLO PUSIERON 11.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
